build:
    zip:
        composer:
            enabled: false
        assets:
            enabled: true
        pack:
            excludes:
                paths:
                    - var
                    - .gitignore
